function result = avoid_rotor_slot(Qr,Qs,p)
% p = pole pairs
if Qr == Qs || Qr == 0.5*Qs || Qr == 2*Qs || Qr == Qs + 2*p ||...
        Qr == Qs - 2*p || Qr == 2*Qs + 2*p || Qr == 2*Qs - 2*p ||...
        Qr == Qs + p || Qr == Qs - p || Qr == 0.5*Qs + p ||...
        Qr == 0.5*Qs - p || Qr > 1.25*Qs
    result = 0;
else
    for n = 1:10
        if Qr == 6*p*n || Qr == 6*p*n + 2*p || Qr == 6*p*n - 2*p ||...
                Qr == 6*p*n + 1 || Qr == 6*p*n - 1 ||...
                Qr == 6*p*n + 2*p + 1 || Qr == 6*p*n + 2*p - 1 ||...
                Qr == 6*p*n - 2*p + 1 || Qr == 6*p*n - 2*p - 1 ||...
                Qr == 6*p*n + 2*p || Qr == 6*p*n - 2*p
            result = 0;
        else
            result = 1;
        end
    end
end
%result = Qr*Qs*p;
end