(function(){var a=this;var d=String.prototype.trim?function(b){return b.trim()}:function(b){return b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},e=function(b,c){return b<c?-1:b>c?1:0};var f;a:{var m=a.navigator;if(m){var n=m.userAgent;if(n){f=n;break a}}f=""};var p=-1!=f.indexOf("Opera")||-1!=f.indexOf("OPR"),t=-1!=f.indexOf("Trident")||-1!=f.indexOf("MSIE"),u=-1!=f.indexOf("Edge"),v=-1!=f.indexOf("Gecko")&&!(-1!=f.toLowerCase().indexOf("webkit")&&-1==f.indexOf("Edge"))&&!(-1!=f.indexOf("Trident")||-1!=f.indexOf("MSIE"))&&-1==f.indexOf("Edge"),w=-1!=f.toLowerCase().indexOf("webkit")&&-1==f.indexOf("Edge"),x=function(){var b=a.document;return b?b.documentMode:void 0},y;
a:{var z="",A=function(){var b=f;if(v)return/rv\:([^\);]+)(\)|;)/.exec(b);if(u)return/Edge\/([\d\.]+)/.exec(b);if(t)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(b);if(w)return/WebKit\/(\S+)/.exec(b);if(p)return/(?:Version)[ \/]?(\S+)/.exec(b)}();A&&(z=A?A[1]:"");if(t){var B=x();if(null!=B&&B>parseFloat(z)){y=String(B);break a}}y=z}
var C=y,D={},E=function(b){if(!D[b]){for(var c=0,g=d(String(C)).split("."),h=d(String(b)).split("."),q=Math.max(g.length,h.length),r=0;0==c&&r<q;r++){var O=g[r]||"",P=h[r]||"",Q=RegExp("(\\d*)(\\D*)","g"),R=RegExp("(\\d*)(\\D*)","g");do{var k=Q.exec(O)||["","",""],l=R.exec(P)||["","",""];if(0==k[0].length&&0==l[0].length)break;c=e(0==k[1].length?0:parseInt(k[1],10),0==l[1].length?0:parseInt(l[1],10))||e(0==k[2].length,0==l[2].length)||e(k[2],l[2])}while(0==c)}D[b]=0<=c}},F=a.document,G=F&&t?x()||
("CSS1Compat"==F.compatMode?parseInt(C,10):5):void 0;var H;if(!(H=!v&&!t)){var I;if(I=t)I=9<=Number(G);H=I}H||v&&E("1.9.1");t&&E("9");var J=["top","right","bottom","left"],K=function(b,c,g,h){var q={};q.element=b;b={type:"element"};b.spec=q;if(4!=g.length)throw Error("The anchors should be an array of length 4.");c&&(b.alignments=c);for(c=0;c<J.length;++c)g[c]&&(b[J[c]]=g[c]);void 0!==h&&(b.z_index=h);return b};var L={elements:{colorSlot1:{type:"shape",node_id:"color-slot1",background_color_ids:"back1MCColor"},colorSlot2:{type:"shape",node_id:"color-slot2",background_color_ids:"back2MCColor"},product1MCImage:{type:"product",node_id:"product-image"},text1TFText:{type:"text",font_level:1,component_type:"headline",node_id:"headline",font_color_id:"text1TFTextColor",background_color_ids:"back2MCColor"},text2TFText:{type:"text",font_level:2,component_type:"description",node_id:"description",font_color_id:"text2TFTextColor",
background_color_ids:"back1MCColor"},clickTFText:{type:"button",node_id:"button",font_color_id:"clickTFTextColor",background_color_ids:"clickTFBackColor",weight:1/28}},font_scale_strategy:"mega_title",variations:{square1:{calibrations:["AspectRatioGE 2 0","AspectRatioLE 0.5 0"],styles:{clickTFText:{displayType:"nessieButton"},text1TFText:{padding:"15px 0%"},text2TFText:{padding:"15% 0%"}},colorSlot1:K("colorSlot1","",["0","0","text1 0","0"]),colorSlot2:K("colorSlot2","",["text1 top 0","0","text1 bottom 0",
"0"]),product:K("product1MCImage","top left",["0","0","45%","0"]),text1:K("text1TFText","left top",["product 0","","text1 30%",""]),text2:K("text2TFText","left",["text1 10px","button","10px",""]),button:K("clickTFText","right",["text1 5px","","5px","50%"])},square2:{calibrations:["AspectRatioGE 2.5 0","AspectRatioLE 1.5 0"],styles:{clickTFText:{displayType:"nessieButton"},text1TFText:{padding:"0% 10px"},text2TFText:{padding:"10px 0%"}},colorSlot1:K("colorSlot1","",["0","0","product bottom 0","0"]),
product:K("product1MCImage","top left",["0","50%","min(30%, 60px)","0"]),text1:K("text1TFText","left right top bottom",["0","0","product bottom 0px","product 0px"]),text2:K("text2TFText","left",["text1 0px","button","0",""]),button:K("clickTFText","right",["text1 5px","","5px","50%"])},banner:{calibrations:["AspectRatioLE 2 0"],styles:{clickTFText:{backgroundColor:"back1MCColor",displayType:"nessieButton"},text1TFText:{padding:"10% 5%"},text2TFText:{padding:"10%"}},colorSlot1:K("colorSlot1","",["0",
"product right 0","0","0"]),colorSlot2:K("colorSlot2","",["0","button left 50% 0","0","product 0"]),product:K("product1MCImage","left top",["0","70%","0","0"]),text1:K("text1TFText","top bottom",["","min(button 10px, text2 10px)","","product"]),button:K("clickTFText","top bottom",["5%","","5%","product"]),text2:K("text2TFText","top bottom",["","","","min(button 10px, 60%)"])},tower:{calibrations:["AspectRatioGE 0.8 0"],styles:{clickTFText:{displayType:"nessieButton"},text1TFText:{padding:"20% 0%"}},
colorSlot1:K("colorSlot1","",["0","0","text1 0","0"]),colorSlot2:K("colorSlot2","",["text1 top 0","0","text1 bottom 0","0"]),product:K("product1MCImage","left top",["0","0","70%","0"]),text1:K("text1TFText","left right top",["product 0","10%","40%","10%"]),text2:K("text2TFText","left right top bottom",["text1 2%","10%","button","10%"]),button:K("clickTFText","left right bottom",["70%","","5%",""])},smallSquare:{calibrations:["AspectRatioGE 2 0"],styles:{text1TFText:{color:"#000"},text2TFText:{color:"#000"},
clickTFText:{displayType:"nessieButton"}},product:K("product1MCImage","top",["0","0","63%","0"]),text1:K("text1TFText","",["product","7%","button","7%"]),text2:K("text2TFText","",["product","7%","button","7%"],1),button:K("clickTFText","bottom",["70%","","",""])},smallBanner:{calibrations:["AspectRatioLE 0.5 0"],styles:{text1TFText:{color:"#000"},text2TFText:{color:"#000"},clickTFText:{displayType:"nessieButton"}},product:K("product1MCImage","left",["0","75%","0","0%"]),text1:K("text1TFText","",["5px",
"button","5px","product"]),text2:K("text2TFText","",["2%","button","2%","product"],1),button:K("clickTFText","right",["","","","70%"])}}},M=function(b){b.google_template_data.adData[0].text2TFTextColor="0x000000";window.renderAd(b,L)},N=["onAdData"],S=a;N[0]in S||!S.execScript||S.execScript("var "+N[0]);for(var T;N.length&&(T=N.shift());)N.length||void 0===M?S=S[T]?S[T]:S[T]={}:S[T]=M;})()
